default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

# PostgreSQL configuration
postgres: &postgres
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  # TODO: Set the following environment variables in your .env file
  # username: <%= ENV['DATABASE_USERNAME'] %>
  # password: <%= ENV['DATABASE_PASSWORD'] %>
  # host: <%= ENV['DATABASE_HOST'] %>

development:
  <<: *postgres
  database: auth_horus_development

test:
  <<: *postgres
  database: auth_horus_test

# Store production database in the storage/ directory, which by default
# is mounted as a persistent Docker volume in config/deploy.yml.
production:
  primary:
    <<: *postgres
    database: auth_horus_production
  cache:
    <<: *default
    database: storage/production_cache.sqlite3
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: storage/production_queue.sqlite3
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: storage/production_cable.sqlite3
    migrations_paths: db/cable_migrate
